
a_asteroid = 1.5 #[ae] большая полуось
albedo = 1
start_era = 0 #[years] начальная ера от перигелия
D_asteroid = 1.7 #[km] диаметр астероида
number_of_points = 100 # кол-во точек на всем периоде наблюдений
end_time = 5 #[years] конец наблюдений

#потом добавлю и конфигурацию для 3Д и эллиптики
